### ISSUE TITLE
Example form not aligning properly

### ISSUE THREAD

**Issue by interestinall** [learn-co-curriculum/html-map-contact-form-code-along#10]
<img width="735" alt="screen shot 2016-05-28 at 7 57 55 am" src="https://cloud.githubusercontent.com/assets/4720348/15627448/ffb5f620-24a9-11e6-9a30-a15d83e5d31e.png">

**Comment by ktravers** [comment]
@pletcher the issue here appears to be in the inline styling. learn is rendering the markdown exactly as written/expected. to fix, i think we need to update the inline styling (even something simple, like `display:block;` would be an improvement)

**Comment by pletcher** [comment]
Thanks, @ktravers -- should be fixed.
