### ISSUE TITLE
Explaining the 'for' attribute

### ISSUE THREAD

**Issue by scirocco21** [learn-co-curriculum/html-map-contact-form-code-along#18]
I've had a hard time understanding how the 'for' attribute works, especially this part of the lesson:
--
On line 3 we use a <label> element to create a text label associated with the form input. By using the for attribute set on the label to match the value of the id attribute in the input this ties the label to the input so that if a user clicks on the text of the label "Name" it will select the input next to it. You can test this on the example below:
Name 
Seb Gertz
--

I'm not sure how the box for 'name' in the example illustrates the use of the 'for' attribute: clicking on "name" in the example doesn't select any input next to it. Is there a way to make the example clearer, or explain this more?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
