### ISSUE TITLE
Possible Edit or Clarification needed

### ISSUE THREAD

**Issue by sandyvern** [learn-co-curriculum/html-map-contact-form-code-along#7]
I had to ask about the last step in this lab as it was giving me an error message:

> After you're finished, make sure you install Firefox if you haven't already as it is required for the screenshot tests to run. Then, type learn command from Terminal to run local tests (Mac), Alternately use the learn-test command for Windows. Then submit a pull request on Github and move on to the next lesson!

And then was told that it may have been left over from when the video was added, but that there were no tests in the repo for this lab. 

Would suggest editing or omitting section so other students don't stumble over the same issue.

**Comment by AnnJohn** [comment]
thanks for catching that. we updated it.
